# Generated by Django 2.1.15 on 2022-04-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('School_name', models.CharField(max_length=30)),
                ('SSC_Percentage', models.IntegerField()),
                ('Describe_Hobbies', models.CharField(max_length=200)),
                ('Achivements', models.CharField(max_length=200)),
            ],
        ),
    ]
